// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aOXfUOvonJreSz9clHdw1RUpFgReaok',
    appId: '1:327029132308:web:fc6b5666e7f41fa17f2b01',
    messagingSenderId: '327029132308',
    projectId: 'socialrisk-9840e',
    authDomain: 'socialrisk-9840e.firebaseapp.com',
    storageBucket: 'socialrisk-9840e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufAXKt7COwexk1VqvPURJVvst8rI-0YU',
    appId: '1:327029132308:android:3762a0ae65b03e797f2b01',
    messagingSenderId: '327029132308',
    projectId: 'socialrisk-9840e',
    storageBucket: 'socialrisk-9840e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbKa3WpeXfd7uVKq6nEyD7ldYQEeokU4',
    appId: '1:327029132308:ios:c644d807aa09ea9d7f2b01',
    messagingSenderId: '327029132308',
    projectId: 'socialrisk-9840e',
    storageBucket: 'socialrisk-9840e.firebasestorage.app',
    iosBundleId: 'com.socialrisk.socialRisk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbbKa3WpeXfd7uVKq6nEyD7ldYQEeokU4',
    appId: '1:327029132308:ios:c644d807aa09ea9d7f2b01',
    messagingSenderId: '327029132308',
    projectId: 'socialrisk-9840e',
    storageBucket: 'socialrisk-9840e.firebasestorage.app',
    iosBundleId: 'com.socialrisk.socialRisk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-aOXfUOvonJreSz9clHdw1RUpFgReaok',
    appId: '1:327029132308:web:ed61de42cdf7e5a67f2b01',
    messagingSenderId: '327029132308',
    projectId: 'socialrisk-9840e',
    authDomain: 'socialrisk-9840e.firebaseapp.com',
    storageBucket: 'socialrisk-9840e.firebasestorage.app',
  );
}
